-- ⚑ Placeholder stock (from landing/js/data.js). Replace with real inventory.
insert into variants (sku, product_id, colourway_id, size, stock) values
  ('PUSAKA:DEEP-TEAL:SM','pusaka','deep-teal','SM',6),
  ('PUSAKA:DEEP-TEAL:LXL','pusaka','deep-teal','LXL',9),
  ('PUSAKA:DEEP-TEAL:2XL','pusaka','deep-teal','2XL',7),
  ('PUSAKA:DEEP-TEAL:3XL','pusaka','deep-teal','3XL',4),
  ('PUSAKA:DEEP-TEAL:4XL','pusaka','deep-teal','4XL',3),
  ('SEMARAK:MAROON:SM','semarak','maroon','SM',5),
  ('SEMARAK:MAROON:LXL','semarak','maroon','LXL',8),
  ('SEMARAK:MAROON:2XL','semarak','maroon','2XL',6),
  ('SEMARAK:MAROON:3XL','semarak','maroon','3XL',5),
  ('SEMARAK:MAROON:4XL','semarak','maroon','4XL',2),
  ('RIMBUN:COCOA:SM','rimbun','cocoa','SM',4),
  ('RIMBUN:COCOA:LXL','rimbun','cocoa','LXL',7),
  ('RIMBUN:COCOA:2XL','rimbun','cocoa','2XL',6),
  ('RIMBUN:COCOA:3XL','rimbun','cocoa','3XL',4),
  ('RIMBUN:COCOA:4XL','rimbun','cocoa','4XL',3),
  ('RENDA:CAMEL:SM','renda','camel','SM',5),
  ('RENDA:CAMEL:LXL','renda','camel','LXL',6),
  ('RENDA:CAMEL:2XL','renda','camel','2XL',8),
  ('RENDA:CAMEL:3XL','renda','camel','3XL',5),
  ('RENDA:CAMEL:4XL','renda','camel','4XL',4),
  ('RENDA:INDIGO:SM','renda','indigo','SM',3),
  ('RENDA:INDIGO:LXL','renda','indigo','LXL',7),
  ('RENDA:INDIGO:2XL','renda','indigo','2XL',6),
  ('RENDA:INDIGO:3XL','renda','indigo','3XL',4),
  ('RENDA:INDIGO:4XL','renda','indigo','4XL',2),
  ('SENJA:MIDNIGHT:SM','senja','midnight','SM',6),
  ('SENJA:MIDNIGHT:LXL','senja','midnight','LXL',9),
  ('SENJA:MIDNIGHT:2XL','senja','midnight','2XL',7),
  ('SENJA:MIDNIGHT:3XL','senja','midnight','3XL',5),
  ('SENJA:MIDNIGHT:4XL','senja','midnight','4XL',3),
  ('ANGGERIK:LILAC:SM','anggerik','lilac','SM',5),
  ('ANGGERIK:LILAC:LXL','anggerik','lilac','LXL',8),
  ('ANGGERIK:LILAC:2XL','anggerik','lilac','2XL',6),
  ('ANGGERIK:LILAC:3XL','anggerik','lilac','3XL',4),
  ('ANGGERIK:LILAC:4XL','anggerik','lilac','4XL',2)
on conflict (sku) do nothing;
